[deps]
AmplNLWriter = "7c4d4715-977e-5154-bfe0-e096adeac482"
MINLPTests = "ee0a3090-8ee9-5cdb-b8cb-8eeba3165522"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
AmplNLWriter = "1"
MINLPTests = "0.6.1"
MathOptInterface = "1.33"
Test = "1.10"
JuMP = "1.28.0"
julia = "1.10"