name = "Uno"
uuid = "1baa60ac-02f7-4b39-a7a8-2f4f58486b05"
authors = ["Alexis Montoison <amontoison@anl.gov>", "Charlie Vanaret <vanaret@zib.de>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OpenBLAS32_jll = "656ef2d0-ae68-5445-9ca0-591084a874a2"
Uno_jll = "396d5378-14f1-5ab1-981d-48acd51740ed"

[weakdeps]
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"

[extensions]
UnoMathOptInterfaceExt = "MathOptInterface"
UnoNLPModelsExt = "NLPModels"

[compat]
LinearAlgebra = "1.10"
MathOptInterface = "1.25"
NLPModels = "0.21.5"
OpenBLAS32_jll = "0.3.24"
Test = "1.10"
Uno_jll = "2.2.1"
julia = "1.10"

[extras]
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["CUTEst", "MathOptInterface", "NLPModels", "Test"]
