name: Build Python wheels
# https://github.com/pypa/cibuildwheel/blob/main/examples/github-minimal.yml

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '*.md'
      - 'LICENSE'
      - '*.cff'

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v5
      
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install Fortran compiler on Windows
        uses: fortran-lang/setup-fortran@main
        with:
          compiler: 'intel'
          version: '2025.0'
        if: matrix.os == 'windows-latest'

      - name: Install Fortran compiler on macOS
        uses: fortran-lang/setup-fortran@main
        with:
          compiler: 'gcc'
          version: '13'
        if: matrix.os == 'macos-latest'
      
      - name: Build wheels
        working-directory: ${{github.workspace}}/interfaces/Python
        uses: pypa/cibuildwheel@v3.3.0
        env:
          CIBW_BUILD: "cp3?-*"
          CIBW_SKIP: "pp*"

          # Step 1: Download
          CIBW_BEFORE_BUILD: >
            bash scripts/download_bqpd.sh

          CIBW_BEFORE_BUILD_WINDOWS: >
            pwsh scripts/download_bqpd.ps1

          # Step 2: Tell scikit-build-core where the static library is
          CIBW_ENVIRONMENT: >
            BQPD="${{github.workspace}}/third_party/bqpd/lib/libbqpd.a"

          CIBW_ENVIRONMENT_WINDOWS: >
            BQPD="${{github.workspace}}/third_party/bqpd/lib/libbqpd.a"
        with:
          output-dir: ${{github.workspace}}/wheelhouse